-- Helpers live outside the exposed Data API schema. Fixed search_path prevents hijacking.
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated;
create function private.is_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.user_roles r join public.profiles p on p.id=r.user_id where r.user_id=auth.uid() and r.role='ADMIN' and p.status='ACTIVE'); $$;
create function private.is_public_property(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.properties p join public.owner_profiles o on o.user_id=p.owner_id join public.profiles u on u.id=p.owner_id where p.id=pid and p.deleted_at is null and p.publication_status='ACTIVE' and p.verification_status='APPROVED' and o.verification_status='APPROVED' and u.status='ACTIVE'); $$;
create function private.owns_property(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.properties where id=pid and owner_id=auth.uid()); $$;
create function private.can_read_property(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select private.is_public_property(pid) or private.owns_property(pid) or private.is_admin(); $$;
create function private.owns_room(rid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.room_types where id=rid and private.owns_property(property_id)); $$;
create function private.can_read_room(rid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.room_types where id=rid and ((is_active and private.is_public_property(property_id)) or private.owns_property(property_id) or private.is_admin())); $$;
create function private.can_read_booking(bid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.bookings where id=bid and (user_id=auth.uid() or private.owns_room(room_type_id) or private.is_admin())); $$;
create function private.can_read_payment(pid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.payments where id=pid and private.can_read_booking(booking_id)); $$;
create function private.in_conversation(cid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.conversation_participants where conversation_id=cid and user_id=auth.uid()); $$;
revoke all on all functions in schema private from public;
grant execute on all functions in schema private to anon, authenticated;
alter table public.profiles enable row level security;
create policy profiles_select on public.profiles for select to anon, authenticated using (id=auth.uid() or private.is_admin());
alter table public.user_roles enable row level security;
create policy user_roles_select on public.user_roles for select to anon, authenticated using (user_id=auth.uid() or private.is_admin());
alter table public.owner_profiles enable row level security;
create policy owner_profiles_select on public.owner_profiles for select to anon, authenticated using (user_id=auth.uid() or private.is_admin());
alter table public.properties enable row level security;
create policy properties_select on public.properties for select to anon, authenticated using (private.is_public_property(id) or owner_id=auth.uid() or private.is_admin());
alter table public.property_media enable row level security;
create policy property_media_select on public.property_media for select to anon, authenticated using (private.can_read_property(property_id));
alter table public.facilities enable row level security;
create policy facilities_select on public.facilities for select to anon, authenticated using (is_active);
alter table public.property_facilities enable row level security;
create policy property_facilities_select on public.property_facilities for select to anon, authenticated using (private.can_read_property(property_id));
alter table public.room_types enable row level security;
create policy room_types_select on public.room_types for select to anon, authenticated using ((is_active and private.is_public_property(property_id)) or private.owns_property(property_id) or private.is_admin());
alter table public.room_type_facilities enable row level security;
create policy room_type_facilities_select on public.room_type_facilities for select to anon, authenticated using (private.can_read_room(room_type_id));
alter table public.room_type_inventory enable row level security;
create policy room_type_inventory_select on public.room_type_inventory for select to anon, authenticated using (private.owns_room(room_type_id) or private.is_admin());
alter table public.pricing_plans enable row level security;
create policy pricing_plans_select on public.pricing_plans for select to anon, authenticated using ((is_active and private.can_read_room(room_type_id)) or private.owns_room(room_type_id) or private.is_admin());
alter table public.bookings enable row level security;
create policy bookings_select on public.bookings for select to anon, authenticated using (private.can_read_booking(id));
alter table public.inventory_allocations enable row level security;
create policy inventory_allocations_select on public.inventory_allocations for select to anon, authenticated using (private.can_read_booking(booking_id));
alter table public.payments enable row level security;
create policy payments_select on public.payments for select to anon, authenticated using (private.can_read_booking(booking_id));
alter table public.payment_events enable row level security;
create policy payment_events_select on public.payment_events for select to anon, authenticated using (private.is_admin());
alter table public.refunds enable row level security;
create policy refunds_select on public.refunds for select to anon, authenticated using (private.can_read_payment(payment_id));
alter table public.payout_simulations enable row level security;
create policy payout_simulations_select on public.payout_simulations for select to anon, authenticated using (owner_id=auth.uid() or private.is_admin());
alter table public.favorites enable row level security;
create policy favorites_select on public.favorites for select to anon, authenticated using (user_id=auth.uid());
alter table public.conversations enable row level security;
create policy conversations_select on public.conversations for select to anon, authenticated using (private.in_conversation(id));
alter table public.conversation_participants enable row level security;
create policy conversation_participants_select on public.conversation_participants for select to anon, authenticated using (private.in_conversation(conversation_id));
alter table public.messages enable row level security;
create policy messages_select on public.messages for select to anon, authenticated using (private.in_conversation(conversation_id));
alter table public.calls enable row level security;
create policy calls_select on public.calls for select to anon, authenticated using (private.in_conversation(conversation_id));
alter table public.notes enable row level security;
create policy notes_select on public.notes for select to anon, authenticated using (user_id=auth.uid());
alter table public.reviews enable row level security;
create policy reviews_select on public.reviews for select to anon, authenticated using ((moderation_status='APPROVED' and private.is_public_property(property_id)) or user_id=auth.uid() or private.is_admin());
alter table public.review_media enable row level security;
create policy review_media_select on public.review_media for select to anon, authenticated using (exists(select 1 from public.reviews r where r.id=review_id));
alter table public.user_restrictions enable row level security;
create policy user_restrictions_select on public.user_restrictions for select to anon, authenticated using (owner_id=auth.uid() or user_id=auth.uid() or private.is_admin());
alter table public.verification_submissions enable row level security;
create policy verification_submissions_select on public.verification_submissions for select to anon, authenticated using (submitted_by=auth.uid() or private.is_admin());
alter table public.reports enable row level security;
create policy reports_select on public.reports for select to anon, authenticated using (reporter_id=auth.uid() or private.is_admin());
alter table public.notifications enable row level security;
create policy notifications_select on public.notifications for select to anon, authenticated using (recipient_id=auth.uid());
alter table public.device_tokens enable row level security;
create policy device_tokens_select on public.device_tokens for select to anon, authenticated using (user_id=auth.uid());
alter table public.policy_acceptances enable row level security;
create policy policy_acceptances_select on public.policy_acceptances for select to anon, authenticated using (user_id=auth.uid());
alter table public.deletion_requests enable row level security;
create policy deletion_requests_select on public.deletion_requests for select to anon, authenticated using (user_id=auth.uid() or private.is_admin());
alter table public.search_history enable row level security;
create policy search_history_select on public.search_history for select to anon, authenticated using (user_id=auth.uid());
alter table public.booking_events enable row level security;
create policy booking_events_select on public.booking_events for select to anon, authenticated using (private.can_read_booking(booking_id));
alter table public.inventory_events enable row level security;
create policy inventory_events_select on public.inventory_events for select to anon, authenticated using (private.owns_room(room_type_id) or private.is_admin());
alter table public.audit_logs enable row level security;
create policy audit_logs_select on public.audit_logs for select to anon, authenticated using (private.is_admin());

-- Explicitly read-only mobile API. No privilege-changing client writes or workflow RPCs.
revoke all on all tables in schema public from anon, authenticated;
grant select on all tables in schema public to anon, authenticated;
revoke all on all functions in schema public from public, anon, authenticated;
grant usage on schema public to anon, authenticated;
